### ISSUE TITLE
Missing license 

### ISSUE THREAD

**Issue by sneg55** [CryptoManiacsZone/mooniswap#39]

**Comment by k06a** [comment]
Thanks for pointing on this. We should add LICENSE file to the root. However each Solidity 0.6.x file contains license name in it first line: https://github.com/CryptoManiacsZone/mooniswap/blob/master/contracts/Mooniswap.sol

**Comment by sneg55** [comment]
my bad I was looking at the sidebar and don't check files itself  
![image](https://user-images.githubusercontent.com/7769371/91058600-816a9380-e5dd-11ea-982d-49b0cdf4494b.png)
